// AUTO-GENERATED by scripts/port-legal.mjs from the original static site's /legal/*.html.
// Legal copy is ported VERBATIM — do not rewrite policy text by hand. Business fields are
// tokenized ({{BUSINESS_NAME}} / {{EMAIL}} / {{PHONE}} / {{ADDRESS}}) and resolved from
// lib/content `business` at render, so they track the (currently DUMMY) values there.
export type LegalDoc = { slug: string; title: string; description: string; updated: string; html: string };

export const legalDocs: LegalDoc[] = [
  {
    slug: "privacy",
    title: "Privacy & Data Protection",
    description: "How our independent AT&amp;T Authorized Reseller collects, uses, shares, and protects your personal information, plus your privacy rights and opt-out choices.",
    updated: "Last updated: July 9, 2026 &middot; Effective: July 9, 2026",
    html: `
  <div class="legal-toc">
    <h2>On this page</h2>
    <ol>
      <li><a href="#s1">Overview and scope</a></li>
      <li><a href="#s2">Information we collect</a></li>
      <li><a href="#s3">How we use your information</a></li>
      <li><a href="#s4">How we share information</a></li>
      <li><a href="#s5">Sale or sharing of personal information</a></li>
      <li><a href="#s6">Your privacy rights</a></li>
      <li><a href="#s7">How we protect your data</a></li>
      <li><a href="#s8">How long we keep information</a></li>
      <li><a href="#s9">Children's privacy</a></li>
      <li><a href="#s10">International visitors</a></li>
      <li><a href="#s11">Changes to this notice</a></li>
      <li><a href="#s12">Contact us</a></li>
    </ol>
  </div>

  <div class="callout">
    <p><b>We are an independent authorized reseller.</b> {{BUSINESS_NAME}} is not AT&amp;T Inc., and this is not an official AT&amp;T website. We resell AT&amp;T wireless, device, and Fiber internet products under our reseller authorization. <b>AT&amp;T</b> is a trademark of AT&amp;T Intellectual Property. This notice describes how <em>our</em> business handles your information. AT&amp;T maintains its own separate privacy practices for the network services it ultimately provides.</p>
  </div>

  <h2 id="s1">1. Overview and scope</h2>
  <p>This Privacy &amp; Data Protection Notice explains how {{BUSINESS_NAME}} ("we," "us," or "our") collects, uses, discloses, and safeguards personal information when you visit our website, contact us by phone or email, or purchase products and services through us. It applies to information we gather online and offline in the course of operating our reseller business.</p>
  <p>By using our website or providing information to us, you acknowledge the practices described here. If you do not agree, please do not use our website or submit information to us.</p>

  <h2 id="s2">2. Information we collect</h2>
  <h3>Information you provide to us</h3>
  <ul>
    <li>Contact details such as your name, phone number, email address, and mailing or service address.</li>
    <li>Eligibility and identity details needed to open or transfer service, including a government-issued ID number, date of birth, and credit or financing information used to qualify you for a plan, device installment, or promotion.</li>
    <li>Order and account preferences, trade-in device details, and the content of messages, forms, or requests you send us.</li>
  </ul>
  <h3>Information we collect automatically</h3>
  <ul>
    <li>Technical data such as your IP address, browser and device type, operating system, and referring pages.</li>
    <li>Usage data such as the pages you view, links you click, and how you interact with our site, gathered through cookies and similar technologies. See our <a href="/legal/cookies">Cookies Policy</a> for details.</li>
  </ul>
  <h3>Information from partners and carriers</h3>
  <ul>
    <li>To activate and support your service, we may receive provisioning, order-status, and eligibility information from AT&amp;T and other carriers.</li>
    <li>We may receive verification results from payment processors, identity-verification services, and credit-reporting agencies, and lead information from advertising or referral partners.</li>
  </ul>

  <h2 id="s3">3. How we use your information</h2>
  <ul>
    <li>To process your order and to provision, activate, and support AT&amp;T wireless, device, and Fiber internet service you request.</li>
    <li>To verify identity and eligibility, run credit checks where applicable, and detect, prevent, and investigate fraud.</li>
    <li>To provide customer support, process billing and payments, manage trade-ins, and handle warranty or return requests.</li>
    <li>To send you service and transactional messages about your orders and account.</li>
    <li>To send marketing or promotional communications where you have given the required consent. See our <a href="/legal/tcpa">TCPA Policy</a> for calls and texts.</li>
    <li>To improve our website, products, and customer experience, and to comply with legal obligations and enforce our terms.</li>
  </ul>

  <h2 id="s4">4. How we share information</h2>
  <p>We do not share your personal information except as described below:</p>
  <ul>
    <li><b>With AT&amp;T and other carriers</b> as necessary to provision, activate, and support the products and services you order.</li>
    <li><b>With service providers and processors</b> that perform functions on our behalf — such as payment processing, website hosting, analytics, customer-relationship management, shipping, and identity verification — under contracts that require them to protect your information and use it only for the services they provide to us.</li>
    <li><b>For legal and safety reasons</b>, including to comply with applicable law, respond to lawful requests from public authorities, enforce our agreements, or protect the rights, property, or safety of our customers, our business, or others.</li>
    <li><b>In a business transfer</b>, such as a merger, acquisition, financing, or sale of assets, in which case information may be transferred as a business asset subject to this notice.</li>
  </ul>

  <h2 id="s5">5. Sale or sharing of personal information</h2>
  <p><b>We do not sell your personal information for money.</b> We do not exchange your name, contact details, or account information for payment. Certain uses of cookies and advertising technologies for cross-context behavioral advertising may, however, be treated as a "sale" or "share" under some state privacy laws.</p>
  <div class="callout">
    <p><b>Do Not Sell or Share My Personal Information.</b> To opt out of any such sharing for targeted advertising, you can adjust your cookie preferences on our site or email us at {{EMAIL}} with the subject line "Do Not Sell or Share." We also honor recognized opt-out preference signals, including the Global Privacy Control (GPC), where required by law.</p>
  </div>

  <h2 id="s6">6. Your privacy rights</h2>
  <p>Depending on where you live, you may have some or all of the following rights regarding your personal information:</p>
  <ul>
    <li>The right to access or know what personal information we hold about you.</li>
    <li>The right to correct inaccurate information.</li>
    <li>The right to delete personal information, subject to legal exceptions.</li>
    <li>The right to a portable copy of information you provided.</li>
    <li>The right to opt out of the sale or sharing of personal information and of targeted advertising.</li>
    <li>The right to limit the use of certain sensitive information.</li>
    <li>The right not to receive discriminatory treatment for exercising your rights.</li>
  </ul>
  <p>These rights are provided under laws such as the California Consumer Privacy Act as amended (CCPA/CPRA) and comparable laws in Virginia, Colorado, Connecticut, Utah, and other states. To exercise a right, contact us at {{EMAIL}}. We will verify your request and may ask for information to confirm your identity. You may use an authorized agent where the law permits.</p>

  <h2 id="s7">7. How we protect your data</h2>
  <p>We maintain administrative, technical, and physical safeguards designed to protect personal information. These include encryption of data in transit using TLS, access controls based on least privilege, and monitoring of our systems. Payment card information is handled in accordance with the Payment Card Industry Data Security Standard; see our <a href="/legal/pci-dss">PCI DSS Compliance</a> page. No method of transmission or storage is completely secure, so we cannot guarantee absolute security.</p>

  <h2 id="s8">8. How long we keep information</h2>
  <p>We retain personal information for as long as needed to fulfill the purposes described in this notice, including to provide service and support, and to meet our legal, tax, accounting, and reporting obligations, resolve disputes, and enforce our agreements. When information is no longer required, we delete it or de-identify it.</p>

  <h2 id="s9">9. Children's privacy</h2>
  <p>Our website and services are intended for adults and are not directed to children under 16. We do not knowingly collect personal information from children under 16. If you believe a child has provided us information, please contact {{EMAIL}} and we will take reasonable steps to delete it.</p>

  <h2 id="s10">10. International visitors</h2>
  <p>We operate in the United States, and our services are offered to U.S. residents. If you access our website from outside the United States, understand that your information will be processed and stored in the United States, where data-protection laws may differ from those in your location.</p>

  <h2 id="s11">11. Changes to this notice</h2>
  <p>We may update this notice from time to time to reflect changes in our practices or the law. When we do, we will revise the "Last updated" date above. Material changes will be highlighted on this page. Your continued use of our website after an update means you accept the revised notice.</p>

  <h2 id="s12">12. Contact us</h2>
  <p>To ask a question, exercise a privacy right, or reach our data-protection contact, use any of the following:</p>
  <ul>
    <li>Privacy email: {{EMAIL}}</li>
    <li>Data protection officer: {{EMAIL}}</li>
    <li>General email: {{EMAIL}}</li>
    <li>Phone: {{PHONE}}</li>
    <li>Mail: {{BUSINESS_NAME}}, {{ADDRESS}}</li>
  </ul>
`,
  },
  {
    slug: "disclaimer",
    title: "Disclaimer",
    description: "Important disclaimers for our independent AT&amp;T Authorized Reseller website, including information accuracy, pricing, coverage, third-party links, and liability.",
    updated: "Last updated: July 9, 2026 &middot; Effective: July 9, 2026",
    html: `
  <div class="legal-toc">
    <h2>On this page</h2>
    <ol>
      <li><a href="#s1">Independent reseller status</a></li>
      <li><a href="#s1b">How we are compensated</a></li>
      <li><a href="#s2">Trademarks and ownership</a></li>
      <li><a href="#s3">Information provided "as is"</a></li>
      <li><a href="#s4">Pricing, plans, and promotions</a></li>
      <li><a href="#s5">Coverage, speeds, and network</a></li>
      <li><a href="#s6">Third-party links and content</a></li>
      <li><a href="#s7">No professional advice</a></li>
      <li><a href="#s8">Limitation of liability</a></li>
      <li><a href="#s9">Indemnification</a></li>
      <li><a href="#s10">Governing law</a></li>
      <li><a href="#s11">Contact us</a></li>
    </ol>
  </div>

  <div class="callout">
    <p><b>We are an independent authorized reseller.</b> This website is operated by {{BUSINESS_NAME}}, an independent authorized reseller of AT&amp;T products and services. It is <b>not</b> an official AT&amp;T website, and we are <b>not</b> AT&amp;T Inc. <b>AT&amp;T</b> is a trademark of AT&amp;T Intellectual Property, used here under our reseller authorization.</p>
  </div>

  <h2 id="s1">1. Independent reseller status</h2>
  <p>{{BUSINESS_NAME}} operates as an independent, authorized reseller of AT&amp;T wireless plans, devices, and Fiber internet. We are a separate business from AT&amp;T Inc. and its affiliates. Nothing on this website should be read to suggest that we are AT&amp;T, that we speak for AT&amp;T, or that AT&amp;T is responsible for the content of this site. Statements, opinions, and offers presented here are ours, not AT&amp;T's.</p>

  <h2 id="s1b">How we are compensated</h2>
  <p>We are paid by AT&amp;T when a customer orders AT&amp;T service through us. We receive a commission from AT&amp;T on the plans, devices, and services we sell; we are not paid a fee by you for placing an order, and the price you pay is set by AT&amp;T, not by us. Because our compensation depends on sales, you should treat the descriptions and recommendations on this site as those of an interested seller rather than as impartial advice. Nothing on this site is a promise of a particular price, promotion, or eligibility outcome; AT&amp;T determines all of those at the time your order is placed.</p>

  <h2 id="s2">2. Trademarks and ownership</h2>
  <p>AT&amp;T, the AT&amp;T globe logo, and related names, marks, and slogans are trademarks of AT&amp;T Intellectual Property and/or its affiliates. Other product and company names mentioned on this site are the property of their respective owners. Our use of these marks is nominative and is intended only to identify the products and services we are authorized to resell. For more detail, see our <a href="/legal/trademarks">Trademarks</a> page.</p>

  <h2 id="s3">3. Information provided "as is"</h2>
  <p>The content on this website is provided for general informational purposes only and on an "as is" and "as available" basis. While we work to keep information accurate and current, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, or suitability of the content. Any reliance you place on such information is strictly at your own risk. We may correct, change, or remove content at any time without notice.</p>

  <h2 id="s4">4. Pricing, plans, and promotions</h2>
  <p>Prices, plan features, device offers, trade-in values, and promotions shown on this site are illustrative examples and starting points only. They may not reflect the exact terms available to you and are subject to change without notice. Final pricing, taxes, surcharges, one-time fees, eligibility requirements, and terms are confirmed in writing before you complete an order. All plans, devices, and services are also subject to AT&amp;T's official terms of service, rate plans, and network management policies.</p>
  <ul>
    <li>Advertised device pricing may require an eligible plan, qualifying trade-in, installment agreement, and/or credit approval.</li>
    <li>Promotional offers may have limited availability, expiration dates, and additional conditions.</li>
    <li>Where our information conflicts with AT&amp;T's official terms for a service, AT&amp;T's official terms govern that service.</li>
  </ul>

  <h2 id="s5">5. Coverage, speeds, and network performance</h2>
  <p>Coverage maps, network availability, and speed figures are approximate and are not guarantees. Actual coverage, data speeds, and performance vary based on your location, device, network congestion, terrain, building materials, and other factors outside our control. 5G and Fiber availability depend on your specific address. We do not own or operate the underlying network and cannot guarantee uninterrupted or error-free service.</p>

  <h2 id="s6">6. Third-party links and content</h2>
  <p>Our website may contain links to third-party websites or resources, including AT&amp;T and device manufacturers. We provide these links for convenience only. We do not control, endorse, or assume responsibility for the content, products, privacy practices, or policies of any third-party site. Accessing third-party sites is at your own risk, and their terms and policies apply.</p>

  <h2 id="s7">7. No professional advice</h2>
  <p>Nothing on this website constitutes legal, financial, tax, or other professional advice. The information here is general in nature and may not apply to your particular circumstances. You should consult a qualified professional before making decisions based on any content found on this site.</p>

  <h2 id="s8">8. Limitation of liability</h2>
  <p>To the fullest extent permitted by law, {{BUSINESS_NAME}} and its owners, employees, and agents will not be liable for any direct, indirect, incidental, consequential, special, or punitive damages arising out of or related to your use of, or inability to use, this website or its content, even if we have been advised of the possibility of such damages. Some jurisdictions do not allow certain limitations, so some of these limitations may not apply to you.</p>

  <h2 id="s9">9. Indemnification</h2>
  <p>You agree to indemnify and hold harmless {{BUSINESS_NAME}} and its owners, employees, and agents from any claims, losses, liabilities, and expenses, including reasonable legal fees, arising from your misuse of this website or your violation of these disclaimers or applicable law.</p>

  <h2 id="s10">10. Governing law</h2>
  <p>These disclaimers are governed by the laws of the State of TX, without regard to its conflict-of-laws rules. Any dispute relating to this website will be subject to the exclusive jurisdiction of the state and federal courts located in TX, to the extent permitted by law.</p>

  <h2 id="s11">11. Contact us</h2>
  <p>If you have questions about these disclaimers, please contact us:</p>
  <ul>
    <li>Email: {{EMAIL}}</li>
    <li>Phone: {{PHONE}}</li>
    <li>Mail: {{BUSINESS_NAME}}, {{ADDRESS}}</li>
  </ul>
`,
  },
  {
    slug: "cookies",
    title: "Cookies Policy",
    description: "How our independent AT&amp;T Authorized Reseller uses cookies and similar technologies, the categories involved, and how you can manage your preferences.",
    updated: "Last updated: July 9, 2026 &middot; Effective: July 9, 2026",
    html: `
  <div class="legal-toc">
    <h2>On this page</h2>
    <ol>
      <li><a href="#s1">What cookies are</a></li>
      <li><a href="#s2">Categories of cookies we use</a></li>
      <li><a href="#s3">First-party and third-party cookies</a></li>
      <li><a href="#s4">How long cookies last</a></li>
      <li><a href="#s5">How to manage cookies</a></li>
      <li><a href="#s6">Do Not Track and Global Privacy Control</a></li>
      <li><a href="#s7">Your consent</a></li>
      <li><a href="#s8">Changes to this policy</a></li>
      <li><a href="#s9">Contact us</a></li>
    </ol>
  </div>

  <div class="callout">
    <p><b>We are an independent authorized reseller.</b> This Cookies Policy applies to the website operated by {{BUSINESS_NAME}}, an independent authorized reseller of AT&amp;T products and services. We are <b>not</b> AT&amp;T Inc. <b>AT&amp;T</b> is a trademark of AT&amp;T Intellectual Property. This policy covers only the cookies used on <em>our</em> website.</p>
  </div>

  <h2 id="s1">1. What cookies are</h2>
  <p>Cookies are small text files placed on your device when you visit a website. They allow the site to recognize your device, remember your preferences, and understand how the site is used. We also use similar technologies such as pixels, web beacons, local storage, and software development kits, which we refer to collectively as "cookies" in this policy. Cookies do not run programs or deliver viruses to your device.</p>

  <h2 id="s2">2. Categories of cookies we use</h2>
  <h3>Strictly necessary cookies</h3>
  <p>These are essential for the website to function, such as remembering items you are viewing, maintaining security, and recording your cookie choices. The site cannot work properly without them, so they cannot be switched off through our consent tools.</p>
  <h3>Performance and analytics cookies</h3>
  <p>These help us understand how visitors use our site — which pages are popular and where people encounter difficulty — so we can improve it. For example, we may use Google Analytics to collect aggregated, statistical information about site usage.</p>
  <h3>Functional cookies</h3>
  <p>These remember choices you make, such as your region or preferences, to provide a more personalized experience.</p>
  <h3>Advertising and targeting cookies</h3>
  <p>These are used to make advertising more relevant to you and to measure the effectiveness of our campaigns. For example, we may use Google Ads and the Meta (Facebook) pixel to understand which ads led to visits and to show relevant offers on other sites.</p>

  <h2 id="s3">3. First-party and third-party cookies</h2>
  <ul>
    <li><b>First-party cookies</b> are set by our own website and are generally used for core functionality and our own analytics.</li>
    <li><b>Third-party cookies</b> are set by partners such as analytics and advertising providers when their scripts run on our pages. These partners may use the information they collect in accordance with their own privacy policies.</li>
  </ul>

  <h2 id="s4">4. How long cookies last</h2>
  <ul>
    <li><b>Session cookies</b> are temporary and are deleted when you close your browser.</li>
    <li><b>Persistent cookies</b> remain on your device for a set period or until you delete them, and are used to remember your preferences across visits.</li>
  </ul>

  <h2 id="s5">5. How to manage cookies</h2>
  <p>You have several ways to control cookies:</p>
  <ul>
    <li><b>Consent banner:</b> When required, we present a consent banner where you can accept or decline non-essential cookies and change your choices later.</li>
    <li><b>Browser settings:</b> Most browsers let you block or delete cookies through their settings. Blocking some cookies may affect how the site works.</li>
    <li><b>Advertising industry opt-outs:</b> You can opt out of interest-based advertising from participating companies at the Digital Advertising Alliance's tool at optout.aboutads.info and through your Google Ads Settings.</li>
    <li><b>Analytics opt-out:</b> You can use tools provided by analytics vendors, such as the Google Analytics opt-out browser add-on, to limit that collection.</li>
  </ul>

  <h2 id="s6">6. Do Not Track and Global Privacy Control</h2>
  <p>Some browsers offer a "Do Not Track" (DNT) signal. Because there is no common industry standard for how to respond to DNT, our site does not currently respond to DNT signals. Where required by law, we honor the Global Privacy Control (GPC) as a request to opt out of the sale or sharing of personal information for targeted advertising. For more on your choices, see our <a href="/legal/privacy">Privacy &amp; Data Protection</a> notice.</p>

  <h2 id="s7">7. Your consent</h2>
  <p>Where the law requires it, we rely on your consent to place non-essential cookies, and you may withdraw that consent at any time using the methods above. Strictly necessary cookies are used on the basis of our legitimate interest in operating a secure, functioning website.</p>

  <h2 id="s8">8. Changes to this policy</h2>
  <p>We may update this Cookies Policy to reflect changes in the technologies we use or in the law. When we do, we will update the "Last updated" date above. Please check back periodically to stay informed.</p>

  <h2 id="s9">9. Contact us</h2>
  <p>If you have questions about our use of cookies, contact us:</p>
  <ul>
    <li>Email: {{EMAIL}}</li>
    <li>Privacy email: {{EMAIL}}</li>
    <li>Phone: {{PHONE}}</li>
    <li>Mail: {{BUSINESS_NAME}}, {{ADDRESS}}</li>
  </ul>
`,
  },
  {
    slug: "tcpa",
    title: "TCPA Policy",
    description: "Our TCPA policy explains how we obtain consent for calls and texts, how to opt out, our internal Do-Not-Call practices, and how to reach us with questions.",
    updated: "Last updated: July 9, 2026 &middot; Effective: July 9, 2026",
    html: `
  <div class="legal-toc">
    <h2>On this page</h2>
    <ol>
      <li><a href="#s1">Purpose of this policy</a></li>
      <li><a href="#s2">Prior express written consent</a></li>
      <li><a href="#s3">Consent is not a condition of purchase</a></li>
      <li><a href="#s4">How to opt out</a></li>
      <li><a href="#s5">Do-Not-Call practices</a></li>
      <li><a href="#s6">Calling hours and message frequency</a></li>
      <li><a href="#s7">Message and data rates</a></li>
      <li><a href="#s8">Records of consent</a></li>
      <li><a href="#s9">Call monitoring and recording</a></li>
      <li><a href="#s10">How to file a complaint</a></li>
      <li><a href="#s11">Contact us</a></li>
    </ol>
  </div>

  <div class="callout">
    <p><b>We are an independent authorized reseller.</b> This policy describes the communications practices of {{BUSINESS_NAME}}, an independent authorized reseller of AT&amp;T products and services. We are <b>not</b> AT&amp;T Inc. <b>AT&amp;T</b> is a trademark of AT&amp;T Intellectual Property. Any calls or texts governed by this policy come from us, not from AT&amp;T.</p>
  </div>

  <h2 id="s1">1. Purpose of this policy</h2>
  <p>{{BUSINESS_NAME}} is committed to respecting your communication preferences and to complying with the federal Telephone Consumer Protection Act (TCPA), the Federal Communications Commission's rules, the Telemarketing Sales Rule, and applicable state telemarketing laws. This policy explains how and when we contact you by phone call and text message and the choices you have.</p>

  <h2 id="s2">2. Prior express written consent</h2>
  <p>Before we send marketing or promotional calls or text messages using an automatic telephone dialing system, an artificial or prerecorded voice, or automated texting or AI-generated calling technology, we obtain your prior express written consent. That consent is typically collected through a clearly labeled checkbox or signed agreement in which you provide your phone number and agree to be contacted. We only contact numbers for which we have a lawful basis to do so.</p>

  <h2 id="s3">3. Consent is not a condition of purchase</h2>
  <div class="callout">
    <p><b>Your consent to receive marketing calls or texts is never required to buy anything from us.</b> You can purchase products and services, ask questions, and receive support without agreeing to marketing communications.</p>
  </div>

  <h2 id="s4">4. How to opt out</h2>
  <p>You may withdraw your consent and stop receiving marketing communications from us at any time:</p>
  <ul>
    <li><b>Text messages:</b> Reply <b>STOP</b> or <b>UNSUBSCRIBE</b> to any marketing text to be removed from that program. You may reply <b>HELP</b> for assistance.</li>
    <li><b>Phone calls:</b> Tell the representative you wish to be placed on our internal Do-Not-Call list, or call us at {{PHONE}}.</li>
    <li><b>Email:</b> Send your request to {{EMAIL}} with the phone number you want removed.</li>
  </ul>
  <p>We honor opt-out requests promptly. After you opt out, you may still receive non-marketing transactional messages related to an active order or account unless you ask us to stop those as well.</p>

  <h2 id="s5">5. Do-Not-Call practices</h2>
  <p>We maintain an internal Do-Not-Call list and record your request not to be contacted for marketing purposes. We also honor the National Do Not Call Registry maintained by the Federal Trade Commission and applicable state do-not-call lists. If your number is on these registries, we will not place telemarketing calls to you unless we have an applicable, lawful relationship or your express consent.</p>

  <h2 id="s6">6. Calling hours and message frequency</h2>
  <ul>
    <li>We limit telemarketing calls to the hours permitted by law, generally between 8:00 a.m. and 9:00 p.m. in your local time zone.</li>
    <li>Message frequency varies based on your activity and the programs you join. We do not send an unreasonable number of messages.</li>
  </ul>

  <h2 id="s7">7. Message and data rates</h2>
  <p>Message and data rates may apply to any text messages you send to or receive from us, depending on your mobile plan and carrier. We are not responsible for charges imposed by your carrier. Please check with your carrier for details about your messaging plan.</p>

  <h2 id="s8">8. Records of consent</h2>
  <p>We keep records of the consent you provide, including the date, time, method, and language of the consent, along with any opt-out requests. We retain these records as needed to demonstrate compliance and to honor your preferences.</p>

  <h2 id="s9">9. Call monitoring and recording</h2>
  <p>We may monitor or record calls for quality assurance, training, and recordkeeping purposes. Where the law requires notice or consent for recording, we will provide it at the start of the call. If you do not wish to be recorded, please let the representative know.</p>

  <h2 id="s10">10. How to file a complaint</h2>
  <p>If you believe you received a call or text from us in error or in a manner inconsistent with this policy, please contact us right away at {{PHONE}} or {{EMAIL}} so we can investigate and correct our records. You may also contact the Federal Communications Commission or Federal Trade Commission regarding unwanted calls or texts.</p>

  <h2 id="s11">11. Contact us</h2>
  <p>For any questions about this policy or your communication preferences:</p>
  <ul>
    <li>Email: {{EMAIL}}</li>
    <li>Phone: {{PHONE}}</li>
    <li>Mail: {{BUSINESS_NAME}}, {{ADDRESS}}</li>
  </ul>
`,
  },
  {
    slug: "trademarks",
    title: "Trademarks",
    description: "Trademark attribution and usage notice for our independent AT&amp;T Authorized Reseller, including AT&amp;T marks, third-party marks, and how to raise a concern.",
    updated: "Last updated: July 9, 2026 &middot; Effective: July 9, 2026",
    html: `
  <div class="legal-toc">
    <h2>On this page</h2>
    <ol>
      <li><a href="#s1">Overview</a></li>
      <li><a href="#s2">AT&amp;T trademarks</a></li>
      <li><a href="#s3">The nature of our use</a></li>
      <li><a href="#s4">Third-party trademarks</a></li>
      <li><a href="#s5">Our own marks</a></li>
      <li><a href="#s6">No unauthorized use</a></li>
      <li><a href="#s7">Reporting a trademark concern</a></li>
      <li><a href="#s8">Contact us</a></li>
    </ol>
  </div>

  <div class="callout">
    <p><b>We are an independent authorized reseller.</b> {{BUSINESS_NAME}} is an independent authorized reseller of AT&amp;T products and services. We are <b>not</b> AT&amp;T Inc., and this is <b>not</b> an official AT&amp;T website. Our use of the AT&amp;T name identifies the products and services we are authorized to resell — nothing more.</p>
  </div>

  <h2 id="s1">1. Overview</h2>
  <p>This page explains the trademarks that appear on our website and the basis on which we use them. Trademarks are the names, logos, and slogans that identify the source of a product or service, and they are valuable assets of the companies that own them. We respect the intellectual property rights of others and expect the same courtesy in return.</p>
  <p>We display trademarks only to describe the genuine products and services we offer and to help you recognize them. We do not claim ownership of marks that belong to others, and we do not use any mark to suggest a relationship, sponsorship, or endorsement that does not exist. If you have a question or concern about any mark shown here, please contact us using the details below.</p>

  <h2 id="s2">2. AT&amp;T trademarks</h2>
  <p>AT&amp;T, the AT&amp;T globe logo, and all related names, marks, slogans, and product names are trademarks of AT&amp;T Intellectual Property and/or its affiliates. These marks are owned by AT&amp;T and are used on this website in accordance with our authorization as a reseller. We do not claim any ownership of the AT&amp;T marks, and our authorization does not transfer any ownership rights to us.</p>

  <h2 id="s3">3. The nature of our use</h2>
  <p>Our use of the AT&amp;T name is nominative — that is, we use it truthfully to identify the genuine AT&amp;T products and services we are authorized to sell. This use does not imply, and should not be read to imply, that:</p>
  <ul>
    <li>we are AT&amp;T Inc. or any AT&amp;T affiliate;</li>
    <li>AT&amp;T operates, sponsors, or endorses this website beyond our reseller relationship; or</li>
    <li>we speak on behalf of AT&amp;T.</li>
  </ul>
  <p>We are an independent business, and our relationship with AT&amp;T is limited to our authorized reseller arrangement. See our <a href="/legal/disclaimer">Disclaimer</a> for related information.</p>

  <h2 id="s4">4. Third-party trademarks</h2>
  <p>Names of devices, operating systems, applications, and other products mentioned on this site are trademarks of their respective owners. For example, Apple and iPhone are trademarks of Apple Inc.; Samsung and Galaxy are trademarks of Samsung Electronics Co., Ltd.; and Google, Android, and Pixel are trademarks of Google LLC. Any such reference is for identification only and does not imply any affiliation with or endorsement by those companies.</p>

  <h2 id="s5">5. Our own marks</h2>
  <p>The business name, logo, and any distinctive branding of {{BUSINESS_NAME}} are our own marks or are used under license. You may not use our marks without our prior written permission, and you may not use them in a way that is likely to cause confusion, disparage our business, or suggest an endorsement that does not exist.</p>

  <h2 id="s6">6. No unauthorized use</h2>
  <p>Nothing on this website grants you any right or license to use the AT&amp;T marks, the marks of any third party, or our marks. All rights not expressly granted are reserved by the respective owners. Unauthorized use of any trademark may violate trademark and other laws.</p>
  <p>In particular, you may not copy, reproduce, or recreate the AT&amp;T globe logo or any other AT&amp;T mark, use these marks in your own business name, domain, advertising, or social media, or present yourself as AT&amp;T or as an authorized reseller unless you hold your own valid authorization. If you are a customer sharing your experience with us, you may of course refer to us and to the products we sell by name, provided you do so truthfully and do not imply an official affiliation you do not have.</p>

  <h2 id="s7">7. Reporting a trademark concern</h2>
  <p>If you believe a trademark has been used improperly on this website, or you wish to submit a takedown request, please contact us with the following information so we can respond promptly:</p>
  <ul>
    <li>Your name and contact information.</li>
    <li>Identification of the trademark at issue and the owner you represent.</li>
    <li>The specific location (URL) on our site where the mark appears.</li>
    <li>A description of your concern and the resolution you are requesting.</li>
  </ul>
  <p>We take these concerns seriously and will review and, where appropriate, correct or remove the material in question.</p>

  <h2 id="s8">8. Contact us</h2>
  <p>To raise a trademark question or concern, contact us:</p>
  <ul>
    <li>Email: {{EMAIL}}</li>
    <li>Phone: {{PHONE}}</li>
    <li>Mail: {{BUSINESS_NAME}}, {{ADDRESS}}</li>
  </ul>
`,
  },
  {
    slug: "marketing-policy",
    title: "Marketing Policy",
    description: "Our marketing policy sets standards for truthful advertising, clear disclosures, email and SMS practices, genuine reviews, and partner compliance.",
    updated: "Last updated: July 9, 2026 &middot; Effective: July 9, 2026",
    html: `
  <div class="legal-toc">
    <h2>On this page</h2>
    <ol>
      <li><a href="#s1">Our commitment</a></li>
      <li><a href="#s2">Laws and standards we follow</a></li>
      <li><a href="#s3">Clear and conspicuous disclosures</a></li>
      <li><a href="#s4">Pricing accuracy and no bait-and-switch</a></li>
      <li><a href="#s5">Email marketing</a></li>
      <li><a href="#s6">Text message marketing</a></li>
      <li><a href="#s7">Testimonials and reviews</a></li>
      <li><a href="#s8">Trademark use in advertising</a></li>
      <li><a href="#s9">Affiliates and lead-generation partners</a></li>
      <li><a href="#s10">Report a misleading ad</a></li>
      <li><a href="#s11">Contact us</a></li>
    </ol>
  </div>

  <div class="callout">
    <p><b>We are an independent authorized reseller.</b> All advertising governed by this policy is published by {{BUSINESS_NAME}}, an independent authorized reseller of AT&amp;T products and services. We are <b>not</b> AT&amp;T Inc. Our ads always identify us as an independent reseller and never imply that we are AT&amp;T. <b>AT&amp;T</b> is a trademark of AT&amp;T Intellectual Property.</p>
  </div>

  <h2 id="s1">1. Our commitment</h2>
  <p>{{BUSINESS_NAME}} is committed to advertising that is truthful, accurate, and never deceptive. We believe honest marketing earns trust and repeat business. Our advertisements are designed to give you the information you need to make an informed decision, with material terms disclosed clearly and up front.</p>

  <h2 id="s2">2. Laws and standards we follow</h2>
  <p>Our marketing is designed to comply with applicable advertising laws and platform rules, including:</p>
  <ul>
    <li>The Federal Trade Commission Act and FTC guidance on truthful, substantiated advertising and endorsements.</li>
    <li>The CAN-SPAM Act for commercial email.</li>
    <li>The Telephone Consumer Protection Act for calls and texts (see our <a href="/legal/tcpa">TCPA Policy</a>).</li>
    <li>State unfair and deceptive acts and practices (UDAP) laws.</li>
    <li>Advertising policies of the platforms we use, including Google Ads, Microsoft Advertising, and Meta, including their requirements on trademark use and clear advertiser identity.</li>
  </ul>

  <h2 id="s3">3. Clear and conspicuous disclosures</h2>
  <p>When an offer has conditions, we disclose them clearly and close to the claim they modify. This includes material terms such as eligibility requirements, contract or installment obligations, trade-in conditions, promotional durations, and any fees or taxes not included in an advertised price. We avoid fine print that contradicts the main message of an ad.</p>

  <h2 id="s4">4. Pricing accuracy and no bait-and-switch</h2>
  <p>We advertise prices and offers that are genuinely available. We do not engage in bait-and-switch tactics — that is, we do not advertise a product or price to attract you and then pressure you toward something more expensive. If an advertised item is unavailable or an offer expires, we will tell you honestly. Illustrative pricing is labeled as such, and final pricing is confirmed in writing before you order.</p>

  <h2 id="s5">5. Email marketing</h2>
  <ul>
    <li>Our commercial emails identify us accurately in the "from" and subject lines and include a valid physical mailing address.</li>
    <li>Every marketing email includes a working unsubscribe mechanism, and we honor opt-out requests promptly.</li>
    <li>We do not use deceptive headers or misleading subject lines.</li>
  </ul>

  <h2 id="s6">6. Text message marketing</h2>
  <p>Marketing text messages are sent only with the consent required by law, and you can opt out at any time by replying STOP. Message and data rates may apply. Our full practices for calls and texts are described in our <a href="/legal/tcpa">TCPA Policy</a>.</p>

  <h2 id="s7">7. Testimonials and reviews</h2>
  <p>Any testimonials, reviews, or endorsements we display are genuine and reflect real customer experiences. We do not fabricate reviews or suppress honest negative feedback to create a misleading overall impression. Where an endorser has a material connection to us, we disclose it. Individual results can vary, and testimonials describe those individuals' experiences rather than a guarantee of your results.</p>

  <h2 id="s8">8. Trademark use in advertising</h2>
  <p>We use the AT&amp;T name in advertising only to identify the genuine products and services we are authorized to resell, and always alongside a clear statement that we are an independent authorized reseller. We follow platform-specific rules on trademark use in paid search and social advertising, and we do not use any mark in a way likely to confuse consumers about who we are. See our <a href="/legal/trademarks">Trademarks</a> page.</p>

  <h2 id="s9">9. Affiliates and lead-generation partners</h2>
  <p>If we work with affiliates, publishers, or lead-generation partners, we require them to follow this policy and all applicable laws. Partners may not make false or unsubstantiated claims, may not misrepresent our relationship with AT&amp;T, and may not use spam or non-compliant calling or texting practices. We reserve the right to end any partnership that violates these standards.</p>

  <h2 id="s10">10. Report a misleading ad</h2>
  <p>If you see an advertisement attributed to us that seems inaccurate or misleading, please tell us. Include where you saw the ad, the date, and a description or screenshot if possible. We will investigate promptly and correct any issue we find.</p>

  <h2 id="s11">11. Contact us</h2>
  <p>To ask about this policy or report an ad concern:</p>
  <ul>
    <li>Email: {{EMAIL}}</li>
    <li>Phone: {{PHONE}}</li>
    <li>Mail: {{BUSINESS_NAME}}, {{ADDRESS}}</li>
  </ul>
`,
  },
  {
    slug: "service-fulfillment",
    title: "Service Fulfillment",
    description: "How we fulfill orders: eligibility, pricing and fees, delivery and installation, number porting, returns and exchanges, warranty handling, and support.",
    updated: "Last updated: July 9, 2026 &middot; Effective: July 9, 2026",
    html: `
  <div class="legal-toc">
    <h2>On this page</h2>
    <ol>
      <li><a href="#s1">What we sell and how it's delivered</a></li>
      <li><a href="#s2">Order eligibility and verification</a></li>
      <li><a href="#s3">Pricing, taxes, and fees</a></li>
      <li><a href="#s4">Payment and financing</a></li>
      <li><a href="#s5">Delivery and installation</a></li>
      <li><a href="#s6">Number porting</a></li>
      <li><a href="#s7">Cancellations, returns, and exchanges</a></li>
      <li><a href="#s8">Warranty and defective devices</a></li>
      <li><a href="#s9">Delays and issues</a></li>
      <li><a href="#s10">Escalation and contact</a></li>
    </ol>
  </div>

  <div class="callout">
    <p><b>We are an independent authorized reseller.</b> Orders placed with {{BUSINESS_NAME}} are fulfilled by our independent business as an authorized reseller of AT&amp;T products and services. We are <b>not</b> AT&amp;T Inc. Network service is ultimately provided by AT&amp;T and is subject to AT&amp;T's official terms. <b>AT&amp;T</b> is a trademark of AT&amp;T Intellectual Property.</p>
  </div>

  <h2 id="s1">1. What we sell and how it's delivered</h2>
  <p>We sell AT&amp;T wireless plans, mobile devices and accessories, and home internet including Fiber, along with the activation and setup services that go with them. Depending on the product, fulfillment happens in one of these ways:</p>
  <ul>
    <li><b>Phone orders:</b> Orders are taken by phone and submitted to AT&amp;T for fulfillment.</li>
    <li><b>Shipped devices:</b> When you order a device for delivery, we ship it to the address you provide and help you activate it.</li>
    <li><b>Wireless activation:</b> We provision your line and, where needed, provide or activate a physical SIM or eSIM.</li>
    <li><b>Home internet and Fiber:</b> Installation is scheduled based on serviceability at your address, and may involve a self-install kit or a technician appointment.</li>
  </ul>

  <h2 id="s2">2. Order eligibility and verification</h2>
  <p>Some orders require verification before they can be completed. This may include:</p>
  <ul>
    <li>Identity verification using a valid government-issued ID.</li>
    <li>A credit check for postpaid service, device installment plans, or financing.</li>
    <li>Confirmation that your address is serviceable for the internet or Fiber plan you want.</li>
  </ul>
  <p>If we cannot verify the information needed, we may be unable to complete your order, and we will explain why and discuss alternatives.</p>

  <h2 id="s3">3. Pricing, taxes, and fees</h2>
  <p>Before you place an order, we show you the full price, including the monthly plan cost, applicable taxes and government surcharges, and any one-time fees such as activation or shipping. Advertised pricing is promotional and is confirmed for your specific order before you agree to it.</p>

  <h2 id="s4">4. Payment and financing</h2>
  <p>We accept the payment methods disclosed at checkout. Where offered, devices may be available through an installment or financing agreement that spreads the cost over time, subject to credit approval and separate terms. Any down payment, monthly amount, and total cost will be shown before you agree. Payment card data is handled securely; see our <a href="/legal/pci-dss">PCI DSS Compliance</a> page.</p>

  <h2 id="s5">5. Delivery and installation</h2>
  <ul>
    <li>Wireless activation timing is set by AT&amp;T once your order is submitted.</li>
    <li>Shipped devices are delivered within the timeframe shown at checkout; you will receive tracking information where available.</li>
    <li>Home internet and Fiber installation windows depend on your address and technician availability, and are confirmed before you order.</li>
  </ul>
  <p>Delivery and installation dates are estimates and may be affected by inventory, carrier provisioning, weather, or other factors.</p>

  <h2 id="s6">6. Number porting</h2>
  <p>If you want to keep your current phone number, we can transfer (port) it from your existing carrier. To do this, provide your account number and transfer PIN from your current carrier. Most ports complete within minutes, but some can take longer depending on the losing carrier. Your old service generally remains active until the port completes, so keep it running until your new line is working.</p>

  <h2 id="s7">7. Cancellations, returns, and exchanges</h2>
  <p>Return and exchange terms depend on the product and any applicable AT&amp;T program rules. As a general framework that the store owner should confirm and configure:</p>
  <ul>
    <li>Eligible devices may be returned or exchanged within a <b>14-day</b> return window from the date of purchase or delivery.</li>
    <li>A restocking fee of <b>up to $55</b> may apply to certain returned devices.</li>
    <li>Returned items must be in like-new condition with all original packaging and accessories.</li>
    <li>Service plans may be cancellable subject to the applicable terms; some charges may be non-refundable.</li>
  </ul>
  <p>We will explain the exact return window, any restocking fee, and the refund method that applies to your order before you buy.</p>

  <h2 id="s8">8. Warranty and defective devices</h2>
  <p>New devices are covered by the manufacturer's warranty, and some products may qualify for additional protection plans. If a device is defective or arrives damaged, contact us promptly and we will help you with a manufacturer warranty claim, an exchange where eligible, or another appropriate remedy. Keep your proof of purchase, as it may be required.</p>

  <h2 id="s9">9. Delays and issues</h2>
  <p>If your order is delayed, an installation is missed, or something is not working as expected, reach out to us right away. We will investigate, keep you informed, and work to resolve the issue — whether that means rescheduling an installation, replacing a device, correcting an activation, or adjusting a charge that was applied in error.</p>

  <h2 id="s10">10. Escalation and contact</h2>
  <p>If you are not satisfied with a resolution, ask to escalate and a manager will review your case. To reach us:</p>
  <ul>
    <li>Email: {{EMAIL}}</li>
    <li>Phone: {{PHONE}}</li>
    <li>Mail: {{BUSINESS_NAME}}, {{ADDRESS}}</li>
  </ul>
`,
  },
  {
    slug: "pci-dss",
    title: "PCI DSS Compliance",
    description: "How our independent AT&amp;T Authorized Reseller protects payment card data through PCI DSS practices, encryption, tokenization, and strict access controls.",
    updated: "Last updated: July 9, 2026 &middot; Effective: July 9, 2026",
    html: `
  <div class="legal-toc">
    <h2>On this page</h2>
    <ol>
      <li><a href="#s1">Our commitment</a></li>
      <li><a href="#s2">What the PCI DSS is</a></li>
      <li><a href="#s3">How we handle card data</a></li>
      <li><a href="#s4">Encryption and tokenization</a></li>
      <li><a href="#s5">Access controls and monitoring</a></li>
      <li><a href="#s6">Staff handling guidance</a></li>
      <li><a href="#s7">What we will never ask for</a></li>
      <li><a href="#s8">Scope and annual assessment</a></li>
      <li><a href="#s9">Report a security concern</a></li>
      <li><a href="#s10">Contact us</a></li>
    </ol>
  </div>

  <div class="callout">
    <p><b>We are an independent authorized reseller.</b> These payment-security practices are those of {{BUSINESS_NAME}}, an independent authorized reseller of AT&amp;T products and services. We are <b>not</b> AT&amp;T Inc. <b>AT&amp;T</b> is a trademark of AT&amp;T Intellectual Property. This page describes how <em>our</em> business handles payment card data.</p>
  </div>

  <h2 id="s1">1. Our commitment</h2>
  <p>{{BUSINESS_NAME}} is committed to protecting the payment card information of our customers. We handle card payments in a manner designed to align with the Payment Card Industry Data Security Standard (PCI DSS), a set of security requirements created by the major card brands to protect cardholder data everywhere it is processed, stored, or transmitted.</p>

  <h2 id="s2">2. What the PCI DSS is</h2>
  <p>The PCI DSS is an information-security standard for organizations that handle branded credit and debit cards. It was developed by the PCI Security Standards Council, founded by the major card brands, and it applies to any business that stores, processes, or transmits cardholder data. It covers areas such as building and maintaining secure networks, protecting stored cardholder data, encrypting transmissions, restricting access, monitoring systems, and maintaining an information-security policy.</p>
  <p>Following the standard reduces the risk of card fraud and data breaches and helps protect both customers and businesses. While the PCI DSS is an industry standard rather than a government law, we treat it as an important benchmark for how we handle your payment information.</p>

  <h2 id="s3">3. How we handle card data</h2>
  <ul>
    <li>We use PCI-DSS-validated payment processors and gateways to handle card transactions.</li>
    <li>We do <b>not</b> store full payment card numbers or card verification values (CVV/CVC) on our own systems.</li>
    <li>Where card details are entered, they are captured through our payment provider's secure systems rather than retained by us.</li>
  </ul>

  <h2 id="s4">4. Encryption and tokenization</h2>
  <p>Card data is protected using encryption in transit through industry-standard Transport Layer Security (TLS) when it travels between your device, our site, and our payment provider. Where recurring or stored payments are supported, our providers use tokenization, replacing sensitive card numbers with a non-sensitive token so that the actual card number is not exposed in our environment.</p>

  <h2 id="s5">5. Access controls and monitoring</h2>
  <ul>
    <li>Access to payment-related systems is restricted on a least-privilege, need-to-know basis.</li>
    <li>Individuals with access use unique credentials, and we support strong authentication.</li>
    <li>We and our providers monitor systems for suspicious activity and maintain logging to support investigation.</li>
  </ul>

  <h2 id="s6">6. Staff handling guidance</h2>
  <p>Our team is instructed never to record full card numbers or CVV codes in email, chat, notes, or other insecure locations. When a payment is taken, it is processed directly through our secure payment tools. Staff receive guidance on recognizing and reporting suspicious requests, phishing attempts, and potential fraud.</p>

  <h2 id="s7">7. What we will never ask for</h2>
  <div class="callout">
    <p><b>We will never ask you to send full payment card details by email or text message.</b> If you receive a message claiming to be from us and requesting your full card number, CVV, or PIN in this way, do not respond — it is not a legitimate request. Please report it to us using the contact details below.</p>
  </div>

  <h2 id="s8">8. Scope and annual assessment</h2>
  <p>Because we rely on validated third-party processors and minimize the card data that touches our own systems, our compliance scope is limited. We complete the appropriate Self-Assessment Questionnaire (SAQ) for our payment setup and review our practices at least annually and when our systems change. We also expect our payment providers to maintain their own PCI DSS validation and can request their compliance documentation.</p>
  <p>You can help keep your payments secure as well: make purchases only through our official website or in our store, look for a secure connection in your browser when entering card details, and never share your full card number, CVV, or PIN in response to an unsolicited message. If something about a payment request feels wrong, pause and contact us directly using the details below.</p>

  <h2 id="s9">9. Report a security concern</h2>
  <p>If you suspect a security issue, a fraudulent charge, or that your card data may have been exposed in connection with a purchase from us, contact us immediately so we can investigate and help protect your account. We recommend you also notify your card issuer or bank right away.</p>

  <h2 id="s10">10. Contact us</h2>
  <p>To report a concern or ask about our payment-security practices:</p>
  <ul>
    <li>Email: {{EMAIL}}</li>
    <li>Privacy email: {{EMAIL}}</li>
    <li>Phone: {{PHONE}}</li>
    <li>Mail: {{BUSINESS_NAME}}, {{ADDRESS}}</li>
  </ul>
`,
  },
];

/* ============================================================
   Token resolution.

   The documents above are written with {{BUSINESS_NAME}} / {{EMAIL}} /
   {{PHONE}} / {{ADDRESS}} tokens. This resolver is the ONLY place they are
   substituted, and it guarantees no token can ever reach the DOM:

     1. tokens whose constant is set are replaced with the real value;
     2. any remaining <li> or <p> that still contains a token is dropped
        whole, because a contact line missing its contact detail is not worth
        rendering;
     3. as a backstop, any stray token left anywhere is removed.

   A production build is blocked while these constants are unset
   (scripts/check-business-constants.mjs), so step 2 only ever applies in dev.
   ============================================================ */
import { business, isSet } from "./business";

const TOKEN_VALUES: Record<string, string | null> = {
  "{{BUSINESS_NAME}}": business.legalName,
  "{{EMAIL}}": business.email,
  "{{PHONE}}": business.phoneDisplay,
  "{{ADDRESS}}": business.address,
};

export function resolveLegalHtml(html: string): string {
  let out = html;

  for (const [token, value] of Object.entries(TOKEN_VALUES)) {
    if (isSet(value)) out = out.split(token).join(value);
  }

  // Drop whole list items / paragraphs that still carry an unresolved token.
  out = out.replace(/<li\b[^>]*>[\s\S]*?<\/li>/g, (m) => (m.includes("{{") ? "" : m));
  out = out.replace(/<p\b[^>]*>[\s\S]*?<\/p>/g, (m) => (m.includes("{{") ? "" : m));

  // Backstop: never emit a raw token, whatever the surrounding markup.
  out = out.replace(/\{\{[A-Z_]+\}\}/g, "");

  return out;
}
